// <auto-generated />
using System;
using Exam_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228121253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exam_Management.Entity.ExamDtlsEntity", b =>
                {
                    b.Property<int>("DtlsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DtlsID"));

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<int>("MasterID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("DtlsID");

                    b.HasIndex("MasterID");

                    b.HasIndex("SubjectID");

                    b.ToTable("ExamDtls");
                });

            modelBuilder.Entity("Exam_Management.Entity.ExamMasterEntity", b =>
                {
                    b.Property<int>("MasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterID"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamYear")
                        .HasColumnType("int");

                    b.Property<string>("PassOrFail")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalMark")
                        .HasColumnType("int");

                    b.HasKey("MasterID");

                    b.HasIndex("StudentID");

                    b.ToTable("ExamMasters");
                });

            modelBuilder.Entity("Exam_Management.Entity.StudentEntity", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("StudentID");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Exam_Management.Entity.SubjectEntity", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SubjectID");

                    b.ToTable("SubjectMsts");
                });

            modelBuilder.Entity("Exam_Management.Entity.ExamDtlsEntity", b =>
                {
                    b.HasOne("Exam_Management.Entity.ExamMasterEntity", "ExamMaster")
                        .WithMany("ExamDtls")
                        .HasForeignKey("MasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam_Management.Entity.SubjectEntity", "SubjectEntity")
                        .WithMany("ExamDtls")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamMaster");

                    b.Navigation("SubjectEntity");
                });

            modelBuilder.Entity("Exam_Management.Entity.ExamMasterEntity", b =>
                {
                    b.HasOne("Exam_Management.Entity.StudentEntity", "Student")
                        .WithMany("ExamMasters")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Exam_Management.Entity.ExamMasterEntity", b =>
                {
                    b.Navigation("ExamDtls");
                });

            modelBuilder.Entity("Exam_Management.Entity.StudentEntity", b =>
                {
                    b.Navigation("ExamMasters");
                });

            modelBuilder.Entity("Exam_Management.Entity.SubjectEntity", b =>
                {
                    b.Navigation("ExamDtls");
                });
#pragma warning restore 612, 618
        }
    }
}
